CREATE TABLE Foo (
  id  BIGSERIAL PRIMARY KEY,
  foo INT,
  relatedFooIds BIGINT[]
);

CREATE TABLE Bar (
  id         BIGSERIAL PRIMARY KEY,
  fooId      BIGINT REFERENCES Foo,
  bar        INT,
  otherBarId BIGINT REFERENCES Bar
);

CREATE TABLE FooBar (
  fooId BIGINT REFERENCES Foo,
  barId BIGINT REFERENCES Bar
);

CREATE TABLE Baz (
  id    BIGSERIAL PRIMARY KEY,
  barId BIGINT REFERENCES Bar
);

ALTER TABLE Bar
  ADD COLUMN bazId BIGINT;
ALTER TABLE Bar
  ADD FOREIGN KEY (bazId) REFERENCES Baz;
