name: CI pipeline for development

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
